### ISSUE TITLE
stream the whole topology in one json message 

### ISSUE THREAD

**Issue by haithamwj** [Mellanox-lab/ufm_sdk#6]
we should treat the streaming as snapshot, in which we send one message that contains all streamed API's

it should look like this 

“metadata” : {
                                         "id" : 15,
                                         "timestamp" : “1970-01-01T00:00:01Z”,
                                         “type” : “full”
                                   },
	"links" :      {
                                           “links_list” : [<list of links in the fabric>]
                                   },
	"devices" : {}, 
	"ports" : {
                                           “ports_list” : [<list of ports in the fabric>]
                                  },
	"cables" : {},
	"alarms" : {}

**Comment by mike-dubman** [comment]
maybe also should contain ufm name as part of json.
the receiver will get such data from multiple ufm servers and will need way to distinguish

**Comment by haithamwj** [comment]
> maybe also should contain ufm name as part of json.
> the receiver will get such data from multiple ufm servers and will need way to distinguish

FluentD accept additional parameter called tag in which we could put source of the data instead of adding it in the json itself

**Comment by ananalaghbar** [comment]
Done
