### ISSUE TITLE
Allow connecting to UFM directly from localhost

### ISSUE THREAD

**Issue by kobibar** [Mellanox-lab/ufm_sdk#7]
In UFM Appliance use case, this script will run locally, and therefore, it should connect to UFM directly over 127.0.0.1:<ufm port;  default:8000> directly without credentials rather than via the Apache web server.

**Comment by haithamwj** [comment]
this might be a problem, since UFM expect a username to be provided by apache.

**Comment by kobibar** [comment]
You should add the header {'X-Remote-User': 'ufmsystem'}.

**Comment by ananalaghbar** [comment]
Done
